### ISSUE TITLE
Campos com carecteres acentuados

### ISSUE THREAD

**Issue by daniellopes81** [giovanniramos/PDO4You#10]
Em campos com caracteres acentuados no banco de dados o PDO4You está retornando NULL como se na tabela do banco de dados o campos estivesse realmente vazio.

**Comment by giovanniramos** [comment]
Olá @daniellopes81 ,

vc poderia me encaminhar por e-mail, o código com a qual vc testou e ocorreram esse erros?

**Comment by daniellopes81** [comment]
Detalhes: O erro  apareceu quando fiz uma migração da versão antiga (2.2) para versão mais atual (3.1)
Nesta nova versão percebi que algumas postagens não estavam aparecendo, quando fui verificar mais a fundo percebi que mesmo o banco de dados, no meu caso MySQL, estando em UTF8 em collation “utf8_general_ci”, está retornando os dados truncados.
Veja o Exemplo:
- Banco de Dados:
  Çedilha
- Retorno do PDO4You mais atual:
  �edilha
- Retorno Versão antiga:
  Çedilha

Então tentei postar o mesmo dado com a nova classe e no banco ficou assim:
- Banco de Dados:
  Ã‡edilha
- Retorno do PDO4You mais atual:
  Çedilha.

**Comment by giovanniramos** [comment]
Essa é uma conversão do banco, que na versão 2.2 da classe existia mas foi removido porque só funcionava com o MySQL. Abaixo está o código que você pode incluir após realizar a instância da classe.

$instance = PDO4You::getInstance();

$instance->exec('SET NAMES utf8');
$instance->exec('SET CHARACTER SET utf8');
$instance->exec('SET LC_TIME_NAMES = "pt_BR"');

**Comment by giovanniramos** [comment]
Na atualização recente da classe, versão 3.2, foi adicionado um atributo que define o charset para UTF-8 no MySQL.

Obrigado por reportar.
