### ISSUE TITLE
PostgreSQL

### ISSUE THREAD

**Issue by jotapepinheiro** [giovanniramos/PDO4You#3]
Para que a classe funcione no Postgre tive que comentar algumas linhas, segue:

142 = //self::$instance[$alias]->exec('SET CHARACTER SET utf8');
143 = //self::$instance[$alias]->exec('SET LC_TIME_NAMES = "pt_BR"');
200 = //self::$handle->exec("USE ".self::$database);

**Comment by giovanniramos** [comment]
Obrigado João Paulo, pela colaboração.
Agora tu reacendeu a minha vontade em continuar implementando esta biblioteca.

Neste feriado, estarei refatorando o código e fazendo as devidas atualizações.

**Comment by jotapepinheiro** [comment]
Que bom meu amigo, gostei muito dessa biblioteca, porem eu prefiro usar o 
postgre a mysql.
Conte comigo.

-----Mensagem Original-----

**Comment by giovanniramos** [comment]
Fala João Paulo, 
como eu te prometi antes, refatoração de código completa.
