### ISSUE TITLE
Adição indesejada de caracteres em dados a serem gravados.

### ISSUE THREAD

**Issue by FlacorLopes** [giovanniramos/PDO4You#6]
O método parseJSON acaba gerando um erro mesmo em JSONs válidos como esse:
{
    "query": [
        {
            "table": "teste",
            "values": {
                "Dado": "{stringqualquer:"
            }
        }
    ]
}

Mesmo que isso esteja em dados que se queira gravar  e sendo válido, ele acrescenta um par de aspas duplas em torno da string: {"S":  fazendo a função json_decode não processar o dado por causa das aspas não escapadas.
Se bem que pode-se tirar essa combinação antes de enviar, mesmo assim, acho que isso não funciona como o esperado.

-noob :|

**Comment by giovanniramos** [comment]
Olá @FlacorLopes 
Estarei analisando sua questão e testando.
Em breve, retornarei com a resposta.

**Comment by giovanniramos** [comment]
Corrigido na versão 4.1.
