### ISSUE TITLE
Sugestão

### ISSUE THREAD

**Issue by Davidplic** [giovanniramos/PDO4You#7]
Olá,

Gostei muito do seu projeto. 

Gostaria de sugerir a adição de uma function para a paginação dos resultados já integrada ao sistema com a opção de paginação tanto em GET como em POST.

Aguardo o retorno, obrigado.

**Comment by giovanniramos** [comment]
Olá amigo e obrigado pelo elogio.

Sugestão aceita. Inclusive, eu já havia recebido muitos pedidos do mesmo. 
Porém por falta de tempo o projeto ficou um tanto parado, mas logo em breve estarei retornando com atualizações.

Abraços

**Comment by giovanniramos** [comment]
Olá @Davidplic , desculpe a demora na resposta.

Fiz a adição de uma classe de paginação ao projeto.
Espero que seja útil, abraços

**Comment by giovanniramos** [comment]
Recurso implementado na versão 3.0.
