### ISSUE TITLE
Possivel problema na filtragem de caracteres

### ISSUE THREAD

**Issue by daniellopes81** [giovanniramos/PDO4You#9]
Um problema que percebi foi que caracteres UTF-8 na faixa dos emoji U+1F600 até U+1F6FF

Ou seja quando os envio eles chegam no php mas na hora de gravar no banco via PDO4You ele simplesmente desaparece ou é truncado (??);

Outro erro foi quando enviei : (dois pontos). ele retorna que o json está mal formado.

Existe solução para o caso ?

**Comment by giovanniramos** [comment]
Realmente este é um problema conhecido, ao gravar no banco um registro que contenha o caracter de _dois pontos_, uma solução até mesmo provisória, seria converter esse caracter através do método **htmlColon($string);**

Este método encontra-se no arquivo **PDO4You.library.php**

Quanto aos emoji , vc poderia me enviar seus arquivos de teste ?

**Comment by daniellopes81** [comment]
{
    query : [
            {
                table: "post_comments" ,
                values: { 
                    id_post: 1845,
                    id_user: 1,
                    gmdate_ref: "2013-08-26 13:13:48", 
                    comment: "\ud83d\ude03" 
                }
            }
            ] 
}

Observe no em "comment" tem uma representação unicode de um caracter 'EMOJI".

Se eu tento enviar ele me retorna a exception:
Exception: Mismatch or arithmetic operation modes impossible to be represented.

Acontece o parseJSON

**Comment by daniellopes81** [comment]
Novidades, descobrir que o problema não é por conta dos caracteres emoji, mas sim por conta de TAB que é dado antes da abertura da chave do json
basicamente se eu dou um tab para deixar o json "formatado" : exemplo:

```
      $json = 
           { // aqui é que está o problema na filtragem ele gera um erro por conta da tabulação
            ...
            }
```

acho que mudando esta filtragem ele não gera mais erros

**Comment by giovanniramos** [comment]
Hmmm, este problema está no **parseJSON()** que se utiliza de expressão regular pra fazer a formatação da string, antes de aplicar o **json_decode()** e converter para array.

**Comment by giovanniramos** [comment]
Corrigido na versão 4.1.
Para uso de aspas duplas (**"**) em strings, fazer uso do **addslashes()**
